#Requires -RunAsAdministrator
<#
    SoftwareInjector.psm1
    Pre-installs chosen software into the image, NTLite-style.

    Approach: most installers can't run against an *offline* mounted image
    (they need a live Windows kernel/services), so this copies each
    installer into $OEM$-style staging and appends a silent-install line to
    SetupComplete.cmd, which Windows Setup executes once, automatically,
    the very first time the finished install boots — before the user ever
    sees a desktop. Net effect: apps are "pre-installed" from the user's
    point of view.
#>

function Add-PreinstalledSoftware {
    param(
        [Parameter(Mandatory)][string]$MountDir,
        [Parameter(Mandatory)][string]$ConfigPath
    )
    $cfg = Get-Content $ConfigPath -Raw | ConvertFrom-Json
    $apps = $cfg.Apps | Where-Object { $_.Enabled -eq $true }
    if (-not $apps -or $apps.Count -eq 0) {
        Write-Host "No enabled apps in $ConfigPath — skipping software injection."
        return
    }

    $stagingDir = Join-Path $MountDir "Windows\Setup\Scripts"
    $installersDir = Join-Path $stagingDir "Installers"
    New-Item -ItemType Directory -Path $installersDir -Force | Out-Null

    $setupCompletePath = Join-Path $stagingDir "SetupComplete.cmd"
    $lines = @("@echo off", "REM Auto-generated by TinyBuilderPlus - silent first-boot app installs")

    foreach ($app in $apps) {
        if (-not (Test-Path $app.Source)) {
            Write-Warning "Skipping '$($app.Name)': source not found at $($app.Source)"
            continue
        }
        $fileName = Split-Path $app.Source -Leaf
        Write-Host "Staging installer for $($app.Name) ..."
        Copy-Item -Path $app.Source -Destination (Join-Path $installersDir $fileName) -Force
        $lines += "echo Installing $($app.Name) ..."
        $lines += "`"%~dp0Installers\$fileName`" $($app.SilentArgs)"
    }

    # Preserve any existing SetupComplete.cmd content (append rather than clobber).
    if (Test-Path $setupCompletePath) {
        $existing = Get-Content $setupCompletePath
        $lines = $existing + $lines
    }
    Set-Content -Path $setupCompletePath -Value $lines -Encoding ASCII
    Write-Host "Wrote first-boot install script: $setupCompletePath"
}

Export-ModuleMember -Function Add-PreinstalledSoftware
